# -*- mode: python -*-

Import("env")

env.Library(
    target='cmongo',
    source=[
		'cmongo_shard.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/common',
        '$BUILD_DIR/mongo/db/service_context',
    ]
)
